name: Generate 3D Contribution Graph

on:
  schedule:
    # Runs every 12 hours
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate 3D Graph
        uses: yoshi389111/github-profile-3d-contrib@v1.3.1
        with:
          github_user: ${{ github.repository_owner }}
          file_name: 'profile-3d-contrib.svg'
          # You can change the theme color here
          theme_name: 'GitHub' 
          
      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: update 3d contribution graph'
          file_pattern: 'profile-3d-contrib.svg'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
