name: Generate Snake Animation

on:
  schedule:
    # Runs every 12 hours
    - cron: '0 */12 * * *'
  workflow_dispatch: # Allows manual running from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake SVG (Light)
        uses: Platane/snk@v3
        with:
          # Your GitHub username
          github_user_name: ${{ github.repository_owner }}
          
          # The file to generate
          outputs: |
            dist/github-snake.svg
            
      - name: Generate Snake SVG (Dark)
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake-dark.svg?palette=github-dark
            
      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: update snake contribution graphs'
          file_pattern: 'dist/github-snake*.svg'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
